$(document).ready(function(){jQuery("#load").fadeOut();jQuery("#loading").delay(0).fadeOut("slow");$('#back-to-top').fadeOut();$(window).on("scroll",function(){if($(this).scrollTop()>250){$('#back-to-top').fadeIn(1400);}else{$('#back-to-top').fadeOut(400);}});$('#top').on('click',function(){$('top').tooltip('hide');$('body,html').animate({scrollTop:0},800);return false;});$(".navbar a").on("click",function(event){$(".navbar-collapse").collapse('hide');});$('.iq-accordion .iq-ad-block .ad-details').hide();$('.iq-accordion .iq-ad-block:first').addClass('ad-active').children().slideDown('slow');$('.iq-accordion .iq-ad-block').on("click",function(){if($(this).children('div').is(':hidden')){$('.iq-accordion .iq-ad-block').removeClass('ad-active').children('div').slideUp('slow');$(this).toggleClass('ad-active').children('div').slideDown('slow');}});$('.navbar-nav li a').on('click',function(e){var anchor=$(this);$('html, body').stop().animate({scrollTop:$(anchor.attr('href')).offset().top-0},1500);e.preventDefault();});$(window).on('scroll',function(){if($(this).scrollTop()>100){$('header').addClass('menu-sticky');}else{$('header').removeClass('menu-sticky');}});$('#iq-amazing-tab').on('click','a',function(){$('#iq-amazing-tab  li a.active1').removeClass('active1');$(this).addClass('active1');});var mySkrollr=skrollr.init({forceHeight:false,easings:{easeOutBack:function(p,s){s=1.70158;p=p-1;return(p*p*((s+1)*p+s)+1);}},mobileCheck:function(){return false;}});$('.popup-gallery').magnificPopup({delegate:'a.popup-img',tLoading:'Loading image #%curr%...',type:'image',mainClass:'mfp-img-mobile',gallery:{navigateByImgClick:true,enabled:true,preload:[0,1]},image:{tError:'<a href="%url%">The image #%curr%</a> could not be loaded.'}});$('.popup-youtube, .popup-vimeo, .popup-gmaps').magnificPopup({type:'iframe',disableOn:700,mainClass:'mfp-fade',preloader:false,removalDelay:160,fixedContentPos:false});$('#countdown').countdown({date:'10/01/2019 23:59:59',day:'Day',days:'Days'});$('.iq-progress-bar > span').each(function(){var $this=$(this);var width=$(this).data('percent');$this.css({'transition':'width 2s'});setTimeout(function(){$this.appear(function(){$this.css('width',width+'%');});},500);});$('.iq-widget-menu > ul > li > a').on('click',function(){var checkElement=$(this).next();$('.iq-widget-menu li').removeClass('active');$(this).closest('li').addClass('active');if((checkElement.is('ul'))&&(checkElement.is(':visible'))){$(this).closest('li').removeClass('active');checkElement.slideUp('normal');}
if((checkElement.is('ul'))&&(!checkElement.is(':visible'))){$('.iq-widget-menu ul ul:visible').slideUp('normal');checkElement.slideDown('normal');}
if($(this).closest('li').find('ul').children().length===0){return true;}else{return false;}});$('.timer').countTo();$(window).on('scroll',function(e){if($('#how-it-works').length&&$('#great-screenshots').length){if($(this).scrollTop()>=($('#how-it-works').offset().top-2000)){$('#great-screenshots ul li').children('a[aria-selected=true]').addClass('active');e.preventDefault();}}});var slide=$('.slider-single');var slideTotal=slide.length-1;var slideCurrent=-1;function slideInitial(){slide.addClass('proactivede');setTimeout(function(){slideRight();},500);}
function slideRight(){if(slideCurrent<slideTotal){slideCurrent++;}else{slideCurrent=0;}
if(slideCurrent>0){var preactiveSlide=slide.eq(slideCurrent-1);}else{var preactiveSlide=slide.eq(slideTotal);}
var activeSlide=slide.eq(slideCurrent);if(slideCurrent<slideTotal){var proactiveSlide=slide.eq(slideCurrent+1);}else{var proactiveSlide=slide.eq(0);}
slide.each(function(){var thisSlide=$(this);if(thisSlide.hasClass('preactivede')){thisSlide.removeClass('preactivede preactive active proactive').addClass('proactivede');}
if(thisSlide.hasClass('preactive')){thisSlide.removeClass('preactive active proactive proactivede').addClass('preactivede');}});preactiveSlide.removeClass('preactivede active proactive proactivede').addClass('preactive');activeSlide.removeClass('preactivede preactive proactive proactivede').addClass('active');proactiveSlide.removeClass('preactivede preactive active proactivede').addClass('proactive');}
function slideLeft(){if(slideCurrent>0){slideCurrent--;}else{slideCurrent=slideTotal;}
if(slideCurrent<slideTotal){var proactiveSlide=slide.eq(slideCurrent+1);}else{var proactiveSlide=slide.eq(0);}
var activeSlide=slide.eq(slideCurrent);if(slideCurrent>0){var preactiveSlide=slide.eq(slideCurrent-1);}else{var preactiveSlide=slide.eq(slideTotal);}
slide.each(function(){var thisSlide=$(this);if(thisSlide.hasClass('proactivede')){thisSlide.removeClass('preactive active proactive proactivede').addClass('preactivede');}
if(thisSlide.hasClass('proactive')){thisSlide.removeClass('preactivede preactive active proactive').addClass('proactivede');}});preactiveSlide.removeClass('preactivede active proactive proactivede').addClass('preactive');activeSlide.removeClass('preactivede preactive proactive proactivede').addClass('active');proactiveSlide.removeClass('preactivede preactive active proactivede').addClass('proactive');}
var left=$('.slider-left');var right=$('.slider-right');left.on('click',function(){slideLeft();});right.on('click',function(){slideRight();});slideInitial();var wow=new WOW({boxClass:'wow',animateClass:'animated',offset:0,mobile:false,live:true});wow.init();$('.owl-carousel').each(function(){var $carousel=$(this);$carousel.owlCarousel({items:$carousel.data("items"),loop:$carousel.data("loop"),margin:$carousel.data("margin"),nav:$carousel.data("nav"),dots:$carousel.data("dots"),autoplay:$carousel.data("autoplay"),autoplayTimeout:$carousel.data("autoplay-timeout"),navText:['<i class="fa fa-angle-left fa-2x"></i>','<i class="fa fa-angle-right fa-2x"></i>'],responsiveClass:true,responsive:{0:{items:$carousel.data("items-mobile-sm")},480:{items:$carousel.data("items-mobile")},786:{items:$carousel.data("items-tab")},1023:{items:$carousel.data("items-laptop")},1199:{items:$carousel.data("items")}}});});$('#contact').submit(function(e){var flag=0;e.preventDefault();$('.require').each(function(){if($.trim($(this).val())==''){$(this).css("border","1px solid red");e.preventDefault();flag=1;}else{$(this).css("border","1px solid grey");flag=0;}});if(grecaptcha.getResponse()==""){flag=1;alert('Please verify Recaptch');}else{flag=0;}
if(flag==0){$.ajax({url:'php/contact-form.php',type:'POST',data:$("#contact").serialize()}).done(function(data){$("#result").html('Form was successfully submitted.');$('#contact')[0].reset();}).fail(function(){alert('Ajax Submit Failed ...');});}});});